### ISSUE TITLE
getRunningForegroundApps do not get service

### ISSUE THREAD

**Issue by xiangwan** [jaredrummler/AndroidProcesses#11]
hi,
excuse,my english is not good.
your lib is great.
but i did not want *getRunningForegroundApps* return service,
what can i do?

**Comment by jaredrummler** [comment]
By service do you mean apps which run in another process? These processes would have the name {package_name:process_name}. See http://developer.android.com/guide/components/processes-and-threads.html

**Comment by xiangwan** [comment]
sorry,my english is too bad, my point is *ProcessManager.getRunningForegroundApps(context)* return several process ,but i just need one of them，which Interaction with the User。
Thank you for the reply

**Comment by jaredrummler** [comment]
Instead of using `ProcessManager.getRunningForegroundApps(context)` try using `ProcessManager.getRunningAppProcesses()` and check if the `foreground` is true.

```java
String packageName = "REPLACE_WITH_YOUR_PACKAGE_NAME";

List<AndroidAppProcess> processes = ProcessManager.getRunningAppProcesses();
for (AndroidAppProcess process : processes) {
  if (process.getPackageName().equals(packageName)) {
    if (process.foreground) {
      System.out.println("Foreground process: " + process.name);
    }
  }
}
```

If there are multiple processes for the same app, this will print out the process in the foreground.

**Comment by xiangwan** [comment]
￣へ￣ still not work，too many process.foreground is true。
can you fix this *Some information that was available through ActivityManager#getRunningAppProcesses() is not available using this library (pkgList, lru, importance, etc.).*?
then i can use another way ,like this 
`
           ActivityManager.RunningAppProcessInfo currentInfo = null;
            Field field = null;
            final int PROCESS_STATE_TOP = 2;
            field = ActivityManager.RunningAppProcessInfo.class.getDeclaredField("processState");

            List<ActivityManager.RunningAppProcessInfo> apps =              ProcessManager.getRunningAppProcessInfo(context);
                for (ActivityManager.RunningAppProcessInfo app : apps) {

                    if (app.importance == ActivityManager.RunningAppProcessInfo.IMPORTANCE_FOREGROUND
                            && app.importanceReasonCode == ActivityManager.RunningAppProcessInfo.REASON_UNKNOWN) {
                        Integer state = null;
                        try {
                            state = field.getInt(app);
                        } catch (Exception e) {
                        }
                        if (state != null && state == PROCESS_STATE_TOP) {
                            currentInfo = app;
                            break;
                        }
                    }
                }
`

**Comment by jaredrummler** [comment]
You will need to use UsageStatsManager to get the current running app on Android 5.0.1+.

**Comment by xiangwan** [comment]
(╯‵□′)╯︵┻━┻
