### ISSUE TITLE
Problem get topactivity

### ISSUE THREAD

**Issue by fabri8bit** [jaredrummler/AndroidProcesses#15]
I not can get "top activity" app foreground.  My current raw solution:

    Vector<String> getActivePackages() {

        Vector<String> res = new Vector<String>(1, 1);
        List<AndroidAppProcess> processes = ProcessManager.getRunningForegroundApps(getApplicationContext());

        String pk = "";
        String appName = "";

        for (int x = 0; x < processes.size(); x++) {

            LogAndroid.info(TAG, "LIST ->  " + processes.get(x).getPackageName());
        }

        for (int x = 0; x < processes.size(); x++) {

            pk = processes.get(x).getPackageName();

            if (!pk.contains("launcher") && !pk.contains("android.gms")) {

                appName = processes.get(x).name;
                res.add(0, appName);
                res.add(1, pk);
                break;

            } else {

                res.add(0, "");
                res.add(1, "");
                continue;
            }

        }

        LogAndroid.info(TAG, "NAME " + res.get(0));
        LogAndroid.info(TAG, "PK " + res.get(1));
        return res;
    }

help me?

**Comment by jaredrummler** [comment]
It is not possible to get the top activity using this library. You could check the oom_score and it will be somewhat accurate but not guaranteed. Please use UsageStatsManager to get the foreground app on Android 5.1.1+.
