### ISSUE TITLE
Cpu Usage

### ISSUE THREAD

**Issue by moderateepheezy** [jaredrummler/AndroidProcesses#19]
How can I use this library to get all running app cpu usage?

**Comment by franciscofranco** [comment]
Why would you be able to do that? Just use top. adb shell top

**Comment by jaredrummler** [comment]
@moderateepheezy

```java
List<AndroidAppProcess> processes = ProcessManager.getRunningAppProcesses();
for (AndroidAppProcess process : processes) {
    Stat stat = process.stat();
    long cputime = (stat.stime() + stat.utime()) / 100;
}
```

**Comment by moderateepheezy** [comment]
@jaredrummler  Thanks.
I have a running program, I just need a method that can help me calculate the overall CPU usage of a particular pid or package name and give me its result in percentage %
Example

If pid of Facebook app is 23
Then I should have a CPU usage says
Facebook. 21%

**Comment by jaredrummler** [comment]
@moderateepheezy, I *think* `toolbox top` calculates the "CPU%" the same way the above code does. You can Google "calculate CPU% from proc" and there are different methods. I won't be adding this to the library so I'll mark this as wontfix.
