### ISSUE TITLE
How to get pkgList, importance, lru?

### ISSUE THREAD

**Issue by cundong** [jaredrummler/AndroidProcesses#2]
how to get pkgList, importance, lru from your new api ？

**Comment by jaredrummler** [comment]
I need to look into how this is done and if it's possible. A good place to start with this would be here: https://github.com/android/platform_frameworks_base/blob/master/core/java/com/android/internal/app/ProcessStats.java

Pull requests welcome!

**Comment by chasehui** [comment]
How about getting pkgList?
