### ISSUE TITLE
How to judge my app Activity in the tasks is to show or hide state?

### ISSUE THREAD

**Issue by coolstar1204** [jaredrummler/AndroidProcesses#20]
My app has same Activity in Tasks,has on Service set foreground process. use your library get foreground is true only. so how to judge my Activity state? thanks

**Comment by jaredrummler** [comment]
You should use [registerActivityLifecycleCallbacks](http://developer.android.com/reference/android/app/Application.html#registerActivityLifecycleCallbacks(android.app.Application.ActivityLifecycleCallbacks)) or [`UsageStatsManager`](https://developer.android.com/reference/android/app/usage/UsageStatsManager.html).
