### ISSUE TITLE
How to know if a foreground process is a Service?

### ISSUE THREAD

**Issue by dieforrockvn** [jaredrummler/AndroidProcesses#22]
Hi jaredrummler.
I use your lib in my app to check some app is running in foreground, and those apps have some services running in background. Sometime user doesn't open any apps but my service still detect an app running. I think the reason is this app service process run on foreground process. How to know if it is a service?
Thank you.

My code:
// run on a background service
```
List<AndroidAppProcess> runningForegroundApps = AndroidProcesses.getRunningForegroundApps(getApplicationContext());
isExRunning = false;
for (AndroidAppProcess ap : runningForegroundApps) {
                        if (ap.getPackageName().equals("com.example")) {
                            isExRunning = true;
                            break;
                        }
}
```

**Comment by jaredrummler** [comment]
I don't think this is possible using this library. I would look into using UsageStatsManager.
