### ISSUE TITLE
getRunningForegroundApps returning multiple apps

### ISSUE THREAD

**Issue by ssteiner** [jaredrummler/AndroidProcesses#24]
Hi

When I run getRunningforegroundApps when there's an incoming call, I get two processes - one being the dialer, the other being my app. That happens both on the lock screen (where my app can't be on top) and when my app is in the background.. so I'm wondering what I'm missing here. Shouldn't we have one process that is in the foreground? Essentiall, if you have the incoming call overlay, your app may still be visible and can be used so it's fine to report that it's in the foreground.. but when you're on the start screen, or if the device is locked, I'd expect my app to not show up as started.

**Comment by jaredrummler** [comment]
You shouldn't rely on this library to get the foreground app. I would use UsageStatsManager.
