### ISSUE TITLE
Is there any way to get the topActivity?

### ISSUE THREAD

**Issue by monowar1993** [jaredrummler/AndroidProcesses#25]
It will be very helpful if just suggest me a way to get the package name of topActivity in android 6.0.1.
I read your answer here,
https://stackoverflow.com/questions/30619349/android-5-1-1-and-above-getrunningappprocesses-returns-my-application-packag/32366476#32366476?newreg=ef7639c617c24033b0ae7b2493c34c94
But no help. I only need the topActivity.

**Comment by SamBoLuong** [comment]
`List<AndroidAppProcess> runningForegroundApps = AndroidProcesses.getRunningForegroundApps(WatchDogService.this);
                        AndroidAppProcess androidAppProcess = runningForegroundApps.get(runningForegroundApps.size()-1);`

It's worked for me!

**Comment by SamBoLuong** [comment]
`List<AndroidAppProcess> runningForegroundApps = AndroidProcesses.getRunningForegroundApps(WatchDogService.this);

                        AndroidAppProcess androidAppProcess = runningForegroundApps.get(runningForegroundApps.size()-1);`
It's worked for me!

**Comment by SamBoLuong** [comment]
`List<AndroidAppProcess> runningForegroundApps = AndroidProcesses.getRunningForegroundApps(WatchDogService.this);
                        AndroidAppProcess androidAppProcess = runningForegroundApps.get(runningForegroundApps.size()-1);`
It's worked for me!

**Comment by monowar1993** [comment]
Thanks. :)

**Comment by jaredrummler** [comment]
@SamBoLuong's comment is not reliable. Why would you need this? Perhaps I'll look into this more.

**Comment by monowar1993** [comment]
I need to get info about the top activity. Thats why.

**Comment by jaredrummler** [comment]
By top activity, do you mean the foreground app? What information do you need?

**Comment by monowar1993** [comment]
Sorry for late response. I was on a vacation. Yes I need the foreground app.

**Comment by franciscofranco** [comment]
As far as I know this is only possible through the UsageStatsManager. Obviously there's some fuckery involved, but it works.

**Comment by jaredrummler** [comment]
Going to close this. @franciscofranco is right, you should use UsageStatsManager. Also, Google blocked reading `/proc` in Android Nougat, so `UsageStatsManager` is probably the only possible solution unless the device is rooted. Even if you have root access, knowing the foreground app can be tricky. Also, you should be able to determine if your app is in the foreground using [activity lifecycle callbacks](https://developer.android.com/reference/android/app/Application.ActivityLifecycleCallbacks.html), however, I haven't tried this myself.
