### ISSUE TITLE
what is the field "foreground" meanning?

### ISSUE THREAD

**Issue by wuseal** [jaredrummler/AndroidProcesses#29]
I build a Demo run on my device ,and the it prints not only one app in foreground,and then,I hope to understand what is the "foreground " real meanning ,thanks !
![image](https://cloud.githubusercontent.com/assets/9211902/17364329/1b7e1d3c-59b2-11e6-93a6-4c994196f30c.png)
and only "wu.seal.processtracker" is my test demo
I aways think foreground app only can have one

**Comment by wuseal** [comment]
And when i run on android 4.4.4 monitor ,the running app list looks like this 
![image](https://cloud.githubusercontent.com/assets/9211902/17364582/8c55912e-59b3-11e6-8b32-85e01003e3e0.png)
it looks like something has got wrong

**Comment by jaredrummler** [comment]
It means it belongs to the foreground group. It does not mean that it is the app currently in focus. You should probably move to using UsageStatsManager.
