### ISSUE TITLE
Certain pid directories are not readable in Android M

### ISSUE THREAD

**Issue by galapogos** [jaredrummler/AndroidProcesses#31]
Hi,

I've been testing your code to get the foreground process on several devices, and I've noticed that certain pid directories within /proc are not readable (i.e. file.canRead() returns false), hence causing file.isDirectory() to return false, thereby skipping the directory. For example, the pid directory associated with com.android.systemui is readable on Android versions 5.1.1 and below, but not on 6.0.1. I've even tested it on the same device types but different Android versions - 2 Nexus 5 devices, 1 with 5.1.1 and the other with 6.0.1. I'm able to read the pid directory in the L device, but not the M one.

The funny thing is that in adb shell, I'm able to access the directory, as well as the files within such as cgroup and oom_score. I just can't seem to access it programmatically.

Any ideas why, and how to resolve this?

**Comment by jaredrummler** [comment]
> certain pid directories within /proc are not readable

This is correct. In the README, it says:

> System apps will not be included on some Android versions because they have a higher SELinux context.

Your app is given the SELinux context `u:r:untrusted_app` and system apps are given the context `u:r:system_app`. In ADB Shell, run `ls -Z /proc` and you can see the SELinux context of each directory. Unless your device is rooted and you change the library to list and read directories as the root user, it is impossible to get the process information from these directories.

> The funny thing is that in adb shell, I'm able to access the directory, as well as the files within such as cgroup and oom_score. I just can't seem to access it programmatically.

Running as the shell user, you are given a higher SELinux context. You can test this by running `id` in a shell and then `run-as your.package.name` and `id` again.

Also, Google has restricted reading `/proc` on Android Nougat so this library will no longer work on Android 7.0 (see [here](http://stackoverflow.com/questions/38590140/file-system-changes-in-android-nougat)).
