### ISSUE TITLE
Process is foreground 

### ISSUE THREAD

**Issue by dev28081989** [jaredrummler/AndroidProcesses#32]
Hello Sir  how to check if process in foreground

**Comment by jaredrummler** [comment]
Use [AndroidAppProcess#foreground](https://github.com/jaredrummler/AndroidProcesses/blob/master/library/src/main/java/com/jaredrummler/android/processes/models/AndroidAppProcess.java#L35-36). This isn't reliable. I would use UsageStatsManager or activity lifecycle callbacks.
