### ISSUE TITLE
ask a question

### ISSUE THREAD

**Issue by xiongke15117937934** [jaredrummler/AndroidProcesses#35]
public static boolean isAppForegroundRunning(final Context context) {
 		ActivityManager activityManager = (ActivityManager) context.getSystemService(Context.ACTIVITY_SERVICE);
        if (activityManager == null) return false;
        List<ActivityManager.RunningTaskInfo> tasks = activityManager.getRunningTasks(1);
        if (!tasks.isEmpty()) {
            ComponentName topActivity = tasks.get(0).topActivity;
            if (topActivity.getPackageName().equals(context.getPackageName())) {
                return true;
            }
        }
        return false;
    }
- Mobile phone system:Android 4.3
- model:Galaxy Nexus
- Your code:`AndroidProcesses.getRunningForegroundApps(context);`
If an application to exit to the background, but is the downloaded file，`AndroidProcesses.getRunningForegroundApps(context);`In the`foreground==true,`And use the code before the return value to false (the correct value is false),
That means your code judgment is not accurate

**Comment by jaredrummler** [comment]
I know this is a late reply, but I don't have control over this. This mimics running ps in a shell and the state (fg|bg) isn't perfectly reliable.
