### ISSUE TITLE
How to get the length of the time ?

### ISSUE THREAD

**Issue by 631068264** [jaredrummler/AndroidProcesses#38]
I want to get the length of the time from when the app start to run to now. Perhaps how to get when do the app run ?

**Comment by jaredrummler** [comment]
Check out the [demo](https://github.com/jaredrummler/AndroidProcesses/blob/master/demo/src/main/java/com/jaredrummler/android/processes/sample/dialogs/ProcessInfoDialog.java#L77-78)

```java
Stat stat = process.stat();
long bootTime = System.currentTimeMillis() - SystemClock.elapsedRealtime();
long startTime = bootTime + (10 * stat.starttime());
long elapsedTime = System.currentTimeMillis() - startTime;
```

**Comment by 631068264** [comment]
Oh,Thanks.
