### ISSUE TITLE
help,how to get the top of the stack activity?

### ISSUE THREAD

**Issue by lizixian18** [jaredrummler/AndroidProcesses#39]
hello,how to get the top of the stack activity? I want to used on the app lock.

**Comment by jaredrummler** [comment]
You should use UsageStatsManager. Retrieving process information on Android 7.0+ is not possible without root. Attempting to find the top activity using /proc is also tricky and unreliable.

**Comment by lizixian18** [comment]
yes,I have used UsageStatsManager to solve,thanks
