### ISSUE TITLE
How can I get the memory usage by each process

### ISSUE THREAD

**Issue by hanoy11** [jaredrummler/AndroidProcesses#41]
How can I get the memory usage by each process. 
Thanks

**Comment by jaredrummler** [comment]
You can use [Statm](https://github.com/jaredrummler/AndroidProcesses/blob/83bec9dbf232493be0c4a9ea6658d4e877e4d4e6/library/src/main/java/com/jaredrummler/android/processes/models/Statm.java) to get memory usage. Example is in the README or [demo](https://github.com/jaredrummler/AndroidProcesses/blob/master/demo/src/main/java/com/jaredrummler/android/processes/sample/dialogs/ProcessInfoDialog.java). From [proc man page](http://man7.org/linux/man-pages/man5/proc.5.html):

>        /proc/[pid]/statm
>               Provides information about memory usage, measured in pages.
>               The columns are:
> 
>                   size       (1) total program size
>                              (same as VmSize in /proc/[pid]/status)
>                   resident   (2) resident set size
>                              (same as VmRSS in /proc/[pid]/status)
>                   shared     (3) number of resident shared pages (i.e., backed by a file)
>                              (same as RssFile+RssShmem in /proc/[pid]/status)

**Comment by hanoy11** [comment]
Thank you !
