### ISSUE TITLE
Android.com.settings

### ISSUE THREAD

**Issue by ravenet** [jaredrummler/AndroidProcesses#44]
Hi,
It is  great library, and however, when i open settings using it is not open give me list AndroidProcesses.getRunningForegroundApps(getApplicationContext()); with setting package as it is front.

it is happening for other system packages.

How to fix?

**Comment by jaredrummler** [comment]
From the README:

> System apps will not be included on some Android versions because they have a higher SELinux context.

**Comment by ravenet** [comment]
Hi Jare,

So how we could resolve this case using your library?

**Comment by jaredrummler** [comment]
You can't. You should consider using UsageStatsManager. The library will only return your process on Android 7.0+.
