### ISSUE TITLE
ProcessManager depreciated issue. 

### ISSUE THREAD

**Issue by tenzinzero1** [jaredrummler/AndroidProcesses#46]
I am getting ProcessManager depreciated issue and kindly let me know how to fix it.

**Comment by jaredrummler** [comment]
Use [`AndroidProcesses`](https://github.com/jaredrummler/AndroidProcesses/blob/master/library/src/main/java/com/jaredrummler/android/processes/AndroidProcesses.java) instead.

**Comment by tenzinzero1** [comment]
Thanks @jaredrummler
