### ISSUE TITLE
call AndroidProcesses.getRunningForegroundApps(context) from background or foreground contains my app

### ISSUE THREAD

**Issue by nasrinmansour** [jaredrummler/AndroidProcesses#47]
I have problem in nougat , I call a service in my app from UI thread or by an alarm , when I call this method AndroidProcesses.getRunningForegroundApps(context) from alarm my app name  as like as call from UI Thread , that means my app is in foreground . I want to know now I'm in background or in foreground , how can I fix it in android 7?

**Comment by onexuan** [comment]
Android Nougat

Google has significantly restricted access to /proc in Android Nougat. This library will not work on Android 7.0. Please star this issue. To get a list of running processes on Android Nougat you will need to use UsageStatsManager or have root access. Really Google?
