### ISSUE TITLE
proc/${pid}/stat Can't get the process name？

### ISSUE THREAD

**Issue by hiluo** [jaredrummler/AndroidProcesses#49]
hi jaredrummler:
     I find the name of the process has been truncated，in proc/${pid}/stat file

```
u0_a115   16972 1895  713932 189160 ffffffff 00000000 S com.tencent.shootgame     
shell@android:/proc/16972 $ cat stat
16972 (ncent.shootgame) S 1895 16972 0 0 -1 4194624 140228 2945 258 0 4684 781 0 25 20 0 83 0 388083 781172736 57752 4294967295 1 1 0 0 0 0 4612 4096 545293548 4294967295 0 0 17 3 0 0 0 0 0
```

    so,  Stat.getComm() Can't the complete process name !!!!!

```
 public String getComm() {
    return fields[1].replace("(", "").replace(")", "");
  }
```

**Comment by jaredrummler** [comment]
The process name is `ncent.shootgame`, not `(ncent.shootgame)`

**Comment by hiluo** [comment]
Why not “com.tencent shootgame”？
The cmdline gets "com.tencent shootgame"

**Comment by hiluo** [comment]
hi Jared:
    I See related logic from source (fs/proc/base.c)
```
static ssize_t comm_write(struct file *file, const char __user *buf,
				size_t count, loff_t *offset)
{
	struct inode *inode = file_inode(file);
	struct task_struct *p;
	char buffer[TASK_COMM_LEN]; // TASK_COMM_LEN = 16
	const size_t maxlen = sizeof(buffer) - 1;

	memset(buffer, 0, sizeof(buffer));
	if (copy_from_user(buffer, buf, count > maxlen ? maxlen : count))
		return -EFAULT;

	p = get_proc_task(inode);
	if (!p)
		return -ESRCH;

	if (same_thread_group(current, p))
		set_task_comm(p, buffer);
	else
		count = -EINVAL;

	put_task_struct(p);

	return count;
}
```
   so, we can't get  the process full name from proc/pid/stat file

TASK_COMM_LEN's value，As shown in the figure below
![image](https://user-images.githubusercontent.com/5153845/27474937-008a0daa-5836-11e7-9996-3c842117e61b.png)

**Comment by jaredrummler** [comment]
The library gets the process name from `/proc/PID/cmdline`. `AndroidProcess#name` should be correct unless reading cmdline failed.

https://github.com/jaredrummler/AndroidProcesses/blob/master/library/src/main/java/com/jaredrummler/android/processes/models/AndroidProcess.java#L37-47
