### ISSUE TITLE
What is state?

### ISSUE THREAD

**Issue by MuhamedFathy** [jaredrummler/AndroidProcesses#5]
I'm testing all options in library to see what will return, it's all good but i see `state` returns `S`, i thought it's tells "it's a system process" but it's appears on the both system an third party, So it's points to what?

**Comment by jaredrummler** [comment]
The code is well documented. Just read the JavaDoc. 

For [state](https://github.com/jaredrummler/AndroidProcesses/blob/master/library/src/main/java/com/jaredrummler/android/processes/models/Stat.java#L201-218):

<blockquote>
<p>One of the following characters, indicating process state:</p>
<ul>
<li>'R'  Running</li>
<li>'S'  Sleeping in an interruptible wait</li>
<li>'D'  Waiting in uninterruptible disk sleep</li>
<li>'Z'  Zombie</li>
<li>'T'  Stopped (on a signal) or (before Linux 2.6.33) trace stopped</li>
<li>'t'  Tracing stop (Linux 2.6.33 onward)</li>
<li>'W'  Paging (only before Linux 2.6.0)</li>
<li>'X'  Dead (from Linux 2.6.0 onward)</li>
<li>'x'  Dead (Linux 2.6.33 to 3.13 only)</li>
<li>'K'  Wakekill (Linux 2.6.33 to 3.13 only)</li>
<li>'W'  Waking (Linux 2.6.33 to 3.13 only)</li>
<li>'P'  Parked (Linux 3.9 to 3.13 only)</li>
</ul>
</blockquote>

So, if the state is `'S'`, then the process is "sleeping".

**Comment by MuhamedFathy** [comment]
Latest question and please close it after responding, I checked the docs and i was wondering Is `resident size` = current process size?

Thanks for the link and the info.

**Comment by jaredrummler** [comment]
They are not the same. You can google "vmsize vs vmrss" for more info.

**Comment by MuhamedFathy** [comment]
Sorry, but is there anyway to get the app name using this library?
or I must get it manually using `ApplicationInfo` and `PackageManager`?

**Comment by jaredrummler** [comment]
You need to get the app yourself. There is a method to get `PackageInfo` in `AndroidAppProcess`. 

Example:

```java
String appName = appProcess.getPackageInfo(context, 0).applicationInfo.loadLabel(pm).toString();
```

**Comment by MuhamedFathy** [comment]
Wow it's works!
Thanks a lot
