### ISSUE TITLE
Generate and publish Javadoc

### ISSUE THREAD

**Issue by jaredsburrows** [jaredrummler/AndroidProcesses#9]
- Generate Javadoc
- Publish it along with the dependency

See: https://github.com/chrisbanes/gradle-mvn-push/blob/master/gradle-mvn-push.gradle#L95-L112

- Publish it to another branch to view Javadocs on Github

See: http://jaredsburrows.github.io/finance-api/ and https://github.com/jaredsburrows/finance-api/blob/master/publishJavadoc.sh and https://github.com/JakeWharton/libcore-dex

**Comment by jaredrummler** [comment]
Done: http://jaredrummler.github.io/AndroidProcesses/javadoc/

Thanks.

FYI: You should update your link in the example. It gives a 404.

Change

http://jaredsburrows.github.io/FinanceApi/javadoc/

to

http://jaredsburrows.github.io/finance-api/javadoc/
